# Copyright 2026 SZL Holdings — SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: rosie
    app.kubernetes.io/part-of: szl-uds-mesh
    istio-injection: enabled
    szl.ai/doctrine-version: "v11"
