# Copyright 2026 SZL Holdings — SPDX-License-Identifier: Apache-2.0
# Service for rosie — Istio sidecar provides STRICT mTLS (UDS Operator managed).
apiVersion: v1
kind: Service
metadata:
  name: szl-rosie
  namespace: {{ .Values.namespace }}
  labels:
    app: rosie
    app.kubernetes.io/name: rosie
spec:
  selector:
    app: rosie
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
