# Copyright 2026 SZL Holdings — SPDX-License-Identifier: Apache-2.0
# Service for killinchu — Istio ambient dataplane provides STRICT mTLS (UDS
# Operator managed). The mesh/policy-facing port is .Values.service.port; the
# app inside the container listens on .Values.service.targetPort.
apiVersion: v1
kind: Service
metadata:
  name: szl-killinchu
  namespace: {{ .Values.namespace }}
  labels:
    app: killinchu
    app.kubernetes.io/name: killinchu
spec:
  selector:
    app: killinchu
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
