# Copyright 2026 SZL Holdings — SPDX-License-Identifier: Apache-2.0
# Service for yupana — Istio sidecar provides STRICT mTLS (UDS Operator managed).
apiVersion: v1
kind: Service
metadata:
  name: szl-yupana
  namespace: {{ .Values.namespace }}
  labels:
    app: yupana
    app.kubernetes.io/name: yupana
spec:
  selector:
    app: yupana
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
