# Copyright 2026 SZL Holdings — SPDX-License-Identifier: Apache-2.0
# Service for a11oy — Istio sidecar provides STRICT mTLS (UDS Operator managed).
apiVersion: v1
kind: Service
metadata:
  name: szl-a11oy
  namespace: {{ .Values.namespace }}
  labels:
    app: a11oy
    app.kubernetes.io/name: a11oy
spec:
  selector:
    app: a11oy
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
