# Staging environment overrides
# Usage: helm upgrade --install szl-fleet-overlay ./chart -f chart/values/staging.yaml

global:
  domain: staging.uds.dev
  doctrinePinVersion: "v11"
  doctrinePinRef: "749/14/163"
  kernelCommit: "c7c0ba17"
  slsaLevel: "L1"
  ssoGroup: "/szl-operators"
  gatewayName: tenant

apps:
  a11oy:
    enabled: true
    namespace: szl-a11oy
    servicePort: 8080
    metricsPort: 9090
    clientId: uds-szl-a11oy
    displayName: "SZL A11oy"
    peatEnabled: true

  sentra:
    enabled: true
    namespace: szl-sentra
    servicePort: 8080
    metricsPort: 9090
    clientId: uds-szl-sentra
    displayName: "SZL Sentra"
    peatEnabled: true

  amaru:
    enabled: true
    namespace: szl-amaru
    servicePort: 8080
    metricsPort: 9090
    clientId: uds-szl-amaru
    displayName: "SZL Amaru"
    peatEnabled: true

  rosie:
    enabled: true
    namespace: szl-rosie
    servicePort: 8080
    metricsPort: 9090
    clientId: uds-szl-rosie
    displayName: "SZL Rosie"
    peatEnabled: true

  killinchu:
    enabled: true
    namespace: szl-killinchu
    servicePort: 8080
    metricsPort: 9090
    clientId: uds-szl-killinchu
    displayName: "SZL Killinchu"
    peatEnabled: true
