#!/usr/bin/env bash
# Copyright 2026 SZL Holdings
# SPDX-License-Identifier: Apache-2.0
#
# generate-receipt-key.sh
#
# Generates an Ed25519 keypair for szl-receipts DSSE signing and prints
# a kubectl-apply command to create the szl-receipts-ed25519 Secret in
# the pepr-system namespace.
#
# Usage:
#   bash scripts/generate-receipt-key.sh
#   # Follow the output instructions to apply the Secret.
#
# GitOps path (Bitnami sealed-secrets):
#   bash scripts/generate-receipt-key.sh | \
#     kubectl apply -f - --dry-run=client -o yaml | \
#     kubeseal --namespace pepr-system > k8s/secrets/szl-receipts-ed25519.sealedsecret.yaml
#   git add k8s/secrets/szl-receipts-ed25519.sealedsecret.yaml
#   git commit -m "feat: add sealed Ed25519 receipt signing key"
#
# GitHub Actions path:
#   Run this script locally, then add the base64 values as GHA secrets:
#     gh secret set SZL_RECEIPTS_KEY_PRIV --body "<base64-of-key.priv>"
#     gh secret set SZL_RECEIPTS_KEY_PUB  --body "<base64-of-key.pub>"
#
# Requirements:
#   - openssl (Ed25519 support requires OpenSSL >= 1.1.1)
#   - base64
#   - kubectl (optional, for direct apply)
#
# Security:
#   - The private key is generated in a temp dir and shredded after encoding.
#   - NEVER commit the raw PEM files to version control.
#   - NEVER commit the base64-encoded private key to version control.
#   - Use SealedSecret or GitHub Actions secrets to store the key material.
#
# Refs:
#   Pepr Deep Dive: team/zarf-uds-deep-sweep/PEPR_DEEP_DIVE.md
#   Secret spec:    k8s/secrets/szl-receipts-ed25519.yaml
#   SZL_OPERATIONAL_UPGRADES.md U4 (P0, S)

set -euo pipefail

NAMESPACE="${SZL_KEY_NAMESPACE:-pepr-system}"
SECRET_NAME="szl-receipts-ed25519"

echo "=========================================="
echo " SZL Receipt Ed25519 Key Generator"
echo "=========================================="
echo ""

# ── Step 1: Verify openssl supports Ed25519 ──────────────────────────────────
if ! openssl genpkey -algorithm ed25519 -out /dev/null 2>/dev/null; then
  echo "ERROR: openssl does not support Ed25519 key generation."
  echo "       Requires OpenSSL >= 1.1.1. Install or upgrade openssl."
  exit 1
fi
echo "[1/4] openssl Ed25519 support verified ✓"

# ── Step 2: Generate keypair in temp dir ──────────────────────────────────────
TMPDIR=$(mktemp -d)
trap 'shred -u "${TMPDIR}/ed25519.pem" 2>/dev/null || rm -f "${TMPDIR}/ed25519.pem"; rm -rf "${TMPDIR}"' EXIT

PRIV_PEM="${TMPDIR}/ed25519.pem"
PUB_PEM="${TMPDIR}/ed25519.pub.pem"

openssl genpkey -algorithm ed25519 -out "${PRIV_PEM}" 2>/dev/null
openssl pkey -in "${PRIV_PEM}" -pubout -out "${PUB_PEM}" 2>/dev/null

echo "[2/4] Ed25519 keypair generated ✓"
echo "      Key type: Ed25519 (PKCS#8 PEM, OpenSSL format)"
echo "      Honest label: software key — not HSM-custodied"

# ── Step 3: Base64-encode both keys ──────────────────────────────────────────
PRIV_B64=$(base64 -w0 < "${PRIV_PEM}")
PUB_B64=$(base64 -w0 < "${PUB_PEM}")

echo "[3/4] Keys base64-encoded ✓"

# ── Step 4: Print kubectl apply YAML ──────────────────────────────────────────
echo "[4/4] Generating Secret manifest..."
echo ""

cat <<YAML
---
# Generated by scripts/generate-receipt-key.sh
# SECURITY: This YAML contains a PRIVATE KEY. Treat as a secret.
# Apply directly (do not commit to git without sealing first):
#   kubectl apply -f <this-file>.yaml
# Then delete the file:
#   shred -u <this-file>.yaml  # or: rm -P <this-file>.yaml
apiVersion: v1
kind: Secret
metadata:
  name: ${SECRET_NAME}
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/name: szl-receipts
    app.kubernetes.io/component: signing-key
    szl.io/key-type: ed25519
    szl.io/key-purpose: dsse-receipt-signing
  annotations:
    szl.io/generated-by: "scripts/generate-receipt-key.sh"
    szl.io/key-rotation: "manual — rotate annually or on compromise"
    szl.io/honest-label: "software-key — not HSM-custodied"
type: Opaque
data:
  key.priv: ${PRIV_B64}
  key.pub:  ${PUB_B64}
YAML

echo ""
echo "=========================================="
echo " NEXT STEPS"
echo "=========================================="
echo ""
echo " 1. Save the YAML above to a temp file (NOT in this repo):"
echo "      bash scripts/generate-receipt-key.sh > /tmp/szl-receipt-key.yaml"
echo ""
echo " 2. Apply to cluster (pepr-system namespace must exist):"
echo "      kubectl apply -f /tmp/szl-receipt-key.yaml"
echo "      shred -u /tmp/szl-receipt-key.yaml  # delete after apply"
echo ""
echo " 3. For GitOps (SealedSecret path):"
echo "      bash scripts/generate-receipt-key.sh | \\"
echo "        kubeseal --namespace ${NAMESPACE} \\"
echo "        > k8s/secrets/szl-receipts-ed25519.sealedsecret.yaml"
echo "      git add k8s/secrets/szl-receipts-ed25519.sealedsecret.yaml"
echo ""
echo " 4. Verify Pepr is using the key (not demo mode):"
echo "      kubectl logs -n pepr-system -l app=pepr-admission -f | \\"
echo "        grep -E 'HMAC|SZL_HMAC_KEY|UNSIGNED'"
echo "      # Expected: NO 'UNSIGNED-DEMO-KEY-NOT-CONFIGURED' in logs"
echo ""
echo " 5. Add the base64 values as GHA secrets (for CI signing):"
echo "      gh secret set SZL_RECEIPTS_KEY_PRIV --body \"<base64-priv>\""
echo "      gh secret set SZL_RECEIPTS_KEY_PUB  --body \"<base64-pub>\""
echo ""
echo "=========================================="
