# Copyright 2026 SZL Holdings
# SPDX-License-Identifier: Apache-2.0
#
# AuthorizationPolicy generator for the v0.4.0 mesh interconnect design.
# DESIGN ARTIFACT — no cluster access, no network I/O. Emits one Istio
# AuthorizationPolicy per destination workload into mesh/authpolicies/.
#
# Model: ALLOW-with-implicit-deny. Per Istio semantics, when at least one ALLOW
# AuthorizationPolicy selects a workload, every request to that workload that is
# NOT matched by an ALLOW rule is denied. So one ALLOW policy per callee, listing
# the permitted caller SPIFFE principals, fully encodes the 6x6 matrix.
#   Istio AuthorizationPolicy: https://istio.io/latest/docs/reference/config/security/authorization-policy/
#   Istio authz best-practices (ALLOW => implicit deny): https://istio.io/latest/docs/ops/best-practices/security/

from _matrix_gen import MODULES, NS, SA, decision

TRUST_DOMAIN = "cluster.local"

def principal(mod):
    return f"{TRUST_DOMAIN}/ns/{NS[mod]}/sa/{SA[mod]}"

HEADER = """# Copyright 2026 SZL Holdings
# SPDX-License-Identifier: Apache-2.0
#
# GENERATED by mesh/_authpolicy_gen.py from the v0.4.0 authorization matrix.
# Istio AuthorizationPolicy: https://istio.io/latest/docs/reference/config/security/authorization-policy/
# Schema (action ALLOW/DENY, from.source.principals, to.operation): same URL.
# ALLOW-implies-default-deny semantics: https://istio.io/latest/docs/ops/best-practices/security/
"""

def gen_for_callee(callee):
    allowed = []
    for caller in MODULES:
        if caller == callee:
            continue
        verdict, _ = decision(caller, callee)
        if verdict == "ALLOW":
            allowed.append(caller)
    # App label per workload (used as selector). receipts uses app=szl-receipts-server.
    app_label = "szl-receipts-server" if callee == "receipts" else callee
    lines = [HEADER]
    lines.append("---")
    lines.append("apiVersion: security.istio.io/v1")
    lines.append("kind: AuthorizationPolicy")
    lines.append("metadata:")
    lines.append(f"  name: allow-mesh-to-{callee}")
    lines.append(f"  namespace: {NS[callee]}")
    lines.append("  labels:")
    lines.append(f"    app.kubernetes.io/name: {callee}")
    lines.append("    szl.io/component: mesh-authz")
    lines.append("    szl.io/mesh-version: v0.4.0")
    lines.append("spec:")
    lines.append("  selector:")
    lines.append("    matchLabels:")
    lines.append(f"      app: {app_label}")
    lines.append("  action: ALLOW")
    lines.append("  rules:")
    if allowed:
        lines.append("    - from:")
        lines.append("        - source:")
        lines.append("            principals:")
        for caller in allowed:
            lines.append(f'              - "{principal(caller)}"  # {caller}')
        # Allow health + receipt + app HTTP verbs on standard ports.
        lines.append("      to:")
        lines.append("        - operation:")
        lines.append('            ports: ["8080", "7860", "8443"]')
    else:
        # No caller permitted: empty rules => deny everything (defensive; receipts-server
        # still accepts ingress because callers POST TO it, handled in its own policy).
        lines.append("    []  # no module may initiate to this workload")
    return "\n".join(lines) + "\n"

if __name__ == "__main__":
    import os
    outdir = os.path.join(os.path.dirname(__file__), "authpolicies")
    os.makedirs(outdir, exist_ok=True)
    for callee in MODULES:
        fn = os.path.join(outdir, f"allow-mesh-to-{callee}.yaml")
        with open(fn, "w") as f:
            f.write(gen_for_callee(callee))
        print("wrote", fn)
